import type { FieldDefinition } from '@/types/editor'

export const FIELD_DEFINITIONS: FieldDefinition[] = [
  {
    key: 'productCode',
    label: '商品コード',
    category: '商品情報',
    kind: 'text',
    defaultText: '1234567890',
    defaultWidthMm: 32,
    defaultHeightMm: 8,
  },
  {
    key: 'productName',
    label: '商品名称',
    category: '商品情報',
    kind: 'text',
    defaultText: 'サンプル商品',
    defaultWidthMm: 48,
    defaultHeightMm: 10,
  },
  {
    key: 'contentAmount',
    label: '内容量',
    category: '内容表示',
    kind: 'text',
    defaultText: '100',
    defaultWidthMm: 18,
    defaultHeightMm: 8,
  },
  {
    key: 'contentUnit',
    label: '内容量単位',
    category: '内容表示',
    kind: 'text',
    defaultText: 'g',
    defaultWidthMm: 14,
    defaultHeightMm: 8,
  },
  {
    key: 'price',
    label: '価格',
    category: '価格表示',
    kind: 'text',
    defaultText: '税込 398円',
    defaultWidthMm: 28,
    defaultHeightMm: 9,
  },
  {
    key: 'unit',
    label: '単位',
    category: '価格表示',
    kind: 'text',
    defaultText: '1個',
    defaultWidthMm: 16,
    defaultHeightMm: 8,
  },
  {
    key: 'additives',
    label: '添加物',
    category: '品質表示',
    kind: 'text',
    defaultText: '添加物なし',
    defaultWidthMm: 45,
    defaultHeightMm: 10,
  },
  {
    key: 'origin',
    label: '産地',
    category: '品質表示',
    kind: 'text',
    defaultText: '国産',
    defaultWidthMm: 28,
    defaultHeightMm: 8,
  },
  {
    key: 'totalWeight',
    label: '合計重量',
    category: '物流情報',
    kind: 'text',
    defaultText: '500g',
    defaultWidthMm: 24,
    defaultHeightMm: 8,
  },
  {
    key: 'storageTemperature',
    label: '保存温度',
    category: '保存情報',
    kind: 'text',
    defaultText: '10℃以下',
    defaultWidthMm: 30,
    defaultHeightMm: 8,
  },
]
